#!/bin/sh
# build.sh - cross-compile COMRADE.EXE (serial) for MS-DOS with OpenWatcom.
#
#   . ./env.sh        # put OpenWatcom on PATH (or set WATCOM yourself)
#   ./build.sh
#
# Produces dist/COMRADE.EXE (16-bit real-mode, large model).  No mTCP/packet
# driver -- the agent talks over a COM port.
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRC="$ROOT/src"
BUILD="$ROOT/build"
DIST="$ROOT/dist"

: "${WATCOM:?set WATCOM (run '. ./env.sh' first)}"

rm -rf "$BUILD"
mkdir -p "$BUILD" "$DIST"

# Stamp a build version into a generated header.  COMRADE.EXE reports it in
# HELLO, and the bridge (check_update) compares it against the binary on disk to
# tell whether the running agent is up to date.  Form: "<git-hash>[-dirty].<UTC>".
# The git hash says which commit; the timestamp makes every build unique, so a
# rebuild is always detectable as a new version (never a false "up to date").
VER="$(git -C "$ROOT" rev-parse --short=8 HEAD 2>/dev/null || echo nogit)"
if ! git -C "$ROOT" diff --quiet -- "$SRC" build.sh env.sh 2>/dev/null; then
  VER="${VER}-dirty"                                  # uncommitted agent source
fi
VER="${VER}.$(date -u +%Y%m%d%H%M%S)"
printf '/* generated by build.sh -- do not edit */\n#define COMRADE_VERSION "%s"\n' "$VER" > "$SRC/version.h"
echo "  version: $VER"

# 8088 code, large model, warnings-as-errors, optimised.
OPTS="-0 -ml -bt=dos -oh -ok -ot -s -zp2 -zpw -we -ob -ol+ -oi+ ${CEXTRA:-}"
INC="-i=$SRC"

APP="screen keys capture fileops dirlist hwaccess lzss serial resident agent"
for f in $APP; do
  echo "  wpp  src/$f.cpp"
  wpp "$SRC/$f.cpp" $OPTS $INC -fo="$BUILD/$f.obj"
done

echo "  wasm src/isr.asm"
wasm -0 -ml "$SRC/isr.asm" -fo="$BUILD/isr.obj"

echo "  wlink -> dist/COMRADE.EXE"
FILES=""
for o in $APP isr; do
  if [ -z "$FILES" ]; then FILES="$BUILD/$o.obj"; else FILES="$FILES,$BUILD/$o.obj"; fi
done
wlink system dos \
  option map="$BUILD/comrade.map" \
  option eliminate \
  option stack=4096 \
  name "$DIST/COMRADE.EXE" \
  file "$FILES"

echo
echo "Built: $DIST/COMRADE.EXE"
ls -l "$DIST/COMRADE.EXE"
